package info.chenliang.moba;

import info.chenliang.moba.login.LoginServer;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chenliang' at '16-5-9 下午5:43' with Gradle 1.12
 *
 * @author chenliang, @date 16-5-9 下午5:43
 */
public class Main {
    public static void main(String[] args) throws Exception{
        LoginServer loginServer = new LoginServer();
        loginServer.start(4000);
    }
}
