import info.chenliang.moba.Main;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'chenliang' at '16-5-9 下午5:43' with Gradle 1.12
 *
 * @author chenliang, @date 16-5-9 下午5:43
 */
public class MainTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();
        assertTrue("someLibraryMethod should return 'true'", true);

    }
}
